safe: true
lsi: false
pygments: true
markdown: kramdown
gems:
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
